// dart format off
// ignore_for_file: type=lint, unused_element

part of 'intents.dart';

// GENERATED BY os_intents_gen — do not edit.
// Source: os_intents_example|lib/intents.dart

/// Every intent declared in this library, keyed by its id.
///
/// Pass this to `OsIntents.install()` in `main()`, and to
/// `IntentHarness` in tests.
final IntentRegistry $osIntentsRegistry = IntentRegistry({
  'addTask': IntentBinding(
    id: 'addTask',
    invoke: (args) async => addTask(
      title: _require(args['title'] as String?, 'title'),
      dueDate: args['dueDate'] == null ? null : DateTime.fromMillisecondsSinceEpoch(args['dueDate']! as int, isUtc: true),
      project: await _resolveProject(args['project'] as String?),
      priority: args['priority'] == null ? null : Priority.values.byName(args['priority']! as String),
    ),
  ),
  'dueToday': IntentBinding(
    id: 'dueToday',
    invoke: (args) => dueToday(),
  ),
  'countOpenTasks': IntentBinding(
    id: 'countOpenTasks',
    invoke: (args) => countOpenTasks(),
  ),
  'completeTask': IntentBinding(
    id: 'completeTask',
    invoke: (args) => completeTask(
      taskId: _require(args['taskId'] as String?, 'taskId'),
    ),
  ),
}, entities: {
  'Project': EntityBinding(
    typeName: 'Project',
    byIds: (ids) async => (await ProjectResolver().byIds(ids)).map(_encodeProject).toList(),
    matching: (query) async => (await ProjectResolver().matching(query)).map(_encodeProject).toList(),
    suggested: () async => (await ProjectResolver().suggested()).map(_encodeProject).toList(),
  ),
});

/// Started by the plugin when an Execution.background intent fires with no UI
/// engine running. Separate isolate: nothing here shares memory with the app.
@pragma('vm:entry-point')
Future<void> osIntentsBackgroundEntrypoint() =>
    OsIntents.installBackground($osIntentsRegistry);

/// Throws a message the OS can surface, rather than a bare null check.
T _require<T>(T? value, String name) {
  if (value == null) {
    throw ArgumentError('Intent parameter "$name" was missing or null.');
  }
  return value;
}

/// Flattens a ProjectEntity for the method channel.
Map<String, Object?> _encodeProject(ProjectEntity e) => {
        'id': e.id,
        'name': e.name,
        'teamName': e.teamName,
      };

/// Turns the identifier the OS resolved back into a ProjectEntity,
/// using the ProjectResolver declared with @EntityQuery.
Future<ProjectEntity?> _resolveProject(String? id) async {
  if (id == null) return null;
  final found = await ProjectResolver().byIds([id]);
  return found.isEmpty ? null : found.first;
}
