// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents_cli:os_intents sync

import AppIntents
import Foundation
import os_intents_ios

@available(iOS 16.0, *)
struct AddTaskOsIntent: AppIntent {
  static let title: LocalizedStringResource = "Add task"
  static let description = IntentDescription("Creates a new task in the Inbox")
  static let openAppWhenRun = false

  @Parameter(title: "Title", description: "The title of the task")
  var title: String
  @Parameter(title: "Due date")
  var dueDate: Date?

  static var parameterSummary: some ParameterSummary {
    Summary("Add task \(\.$title)") {
      \.$dueDate
    }
  }

  func perform() async throws -> some IntentResult & ProvidesDialog {
    let outcome = try await OsIntentsBridge.shared.invokeBackground(
      id: "addTask",
      args: [
        "title": title,
        "dueDate": dueDate.map { Int($0.timeIntervalSince1970 * 1000) },
      ]
    )
    return .result(dialog: IntentDialog(stringLiteral: outcome.spoken ?? ""))
  }
}


@available(iOS 16.0, *)
struct DueTodayOsIntent: AppIntent {
  static let title: LocalizedStringResource = "Tasks due today"
  static let openAppWhenRun = false

  func perform() async throws -> some IntentResult & ProvidesDialog {
    // Execution.static_: answered from stored state, with no
    // Dart engine started.
    if let stored = OsIntentsBridge.shared.staticResult(for: "dueToday") {
      let outcome = IntentOutcome(wire: stored)
      return .result(dialog: IntentDialog(stringLiteral: outcome.spoken ?? ""))
    }
    // Nothing published yet — usually a first run, before the
    // app has had a chance to call publishStatic. Fall back to
    // running the handler rather than answering with silence.
    let outcome = try await OsIntentsBridge.shared.invokeBackground(
      id: "dueToday",
      args: [:]
    )
    return .result(dialog: IntentDialog(stringLiteral: outcome.spoken ?? ""))
  }
}


@available(iOS 16.0, *)
struct OpenInboxOsIntent: AppIntent {
  static let title: LocalizedStringResource = "Open inbox"
  static let openAppWhenRun = true

  func perform() async throws -> some IntentResult & ProvidesDialog {
    let outcome = try await OsIntentsBridge.shared.invoke(
      id: "openInbox",
      args: [:]
    )
    return .result(dialog: IntentDialog(stringLiteral: outcome.spoken ?? ""))
  }
}


