// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents_cli:os_intents sync

import AppIntents
import Foundation
import os_intents_ios

@objc(OsIntentsDonor)
final class OsIntentsDonor: NSObject, OsIntentsDonating {
  func donate(
    id: String,
    wire: [String: Any],
    completion: @escaping (Bool) -> Void
  ) {
    guard #available(iOS 16.0, *) else {
      completion(false)
      return
    }
    Task {
      switch id {
      case "addTask":
        let intent = AddTaskOsIntent()
        if let value = wire["title"] as? String { intent.title = value }
        if let value = (wire["dueDate"] as? NSNumber).map({ Date(timeIntervalSince1970: $0.doubleValue / 1000) }) { intent.dueDate = value }
        do {
          _ = try await IntentDonationManager.shared.donate(
            intent: intent
          )
          completion(true)
        } catch {
          completion(false)
        }
      case "dueToday":
        let intent = DueTodayOsIntent()
        do {
          _ = try await IntentDonationManager.shared.donate(
            intent: intent
          )
          completion(true)
        } catch {
          completion(false)
        }
      case "openInbox":
        let intent = OpenInboxOsIntent()
        do {
          _ = try await IntentDonationManager.shared.donate(
            intent: intent
          )
          completion(true)
        } catch {
          completion(false)
        }
      default:
        completion(false)
      }
    }
  }
}
