// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents_cli:os_intents sync

import AppIntents
import Foundation
import SwiftUI
import os_intents_ios

enum OsIntentsSnippetActions {
  /// nil below iOS 17, where Button(intent:) does not exist.
  @available(iOS 16.0, *)
  static var builder: OsIntentsSnippetView.ButtonBuilder? {
    if #available(iOS 17.0, *) {
      return button(id:args:label:systemImageName:)
    }
    return nil
  }

  @available(iOS 17.0, *)
  static func button(
    id: String,
    args: [String: Any],
    label: String,
    systemImageName: String?
  ) -> AnyView? {
    switch id {
    case "addTask":
      let intent = AddTaskOsIntent()
      if let value = args["title"] as? String { intent.title = value }
      if let value = (args["dueDate"] as? NSNumber).map({ Date(timeIntervalSince1970: $0.doubleValue / 1000) }) { intent.dueDate = value }
      return AnyView(
        Button(intent: intent) {
          if let systemImageName {
            Label(label, systemImage: systemImageName)
          } else {
            Text(label)
          }
        }
      )
    case "dueToday":
      let intent = DueTodayOsIntent()
      return AnyView(
        Button(intent: intent) {
          if let systemImageName {
            Label(label, systemImage: systemImageName)
          } else {
            Text(label)
          }
        }
      )
    case "openInbox":
      let intent = OpenInboxOsIntent()
      return AnyView(
        Button(intent: intent) {
          if let systemImageName {
            Label(label, systemImage: systemImageName)
          } else {
            Text(label)
          }
        }
      )
    default:
      return nil
    }
  }
}
