// dart format off
// ignore_for_file: type=lint, unused_element

part of 'intents.dart';

// GENERATED BY os_intents_gen — do not edit.
// Source: appfunctions_probe|lib/intents.dart

/// Every intent declared in this library, keyed by its id.
///
/// Pass this to `OsIntents.install()` in `main()`, and to
/// `IntentHarness` in tests.
final IntentRegistry $osIntentsRegistry = IntentRegistry({
  'addTask': IntentBinding(
    id: 'addTask',
    invoke: (args) => addTask(
      title: _require(args['title'] as String?, 'title'),
      dueDate: args['dueDate'] == null ? null : DateTime.fromMillisecondsSinceEpoch(args['dueDate']! as int, isUtc: true),
    ),
  ),
  'dueToday': IntentBinding(
    id: 'dueToday',
    invoke: (args) => dueToday(),
  ),
  'openInbox': IntentBinding(
    id: 'openInbox',
    invoke: (args) => openInbox(),
  ),
});

/// Started by the plugin when an Execution.background intent fires with no UI
/// engine running. Separate isolate: nothing here shares memory with the app.
@pragma('vm:entry-point')
Future<void> osIntentsBackgroundEntrypoint() =>
    OsIntents.installBackground($osIntentsRegistry);

/// Throws a message the OS can surface, rather than a bare null check.
T _require<T>(T? value, String name) {
  if (value == null) {
    throw ArgumentError('Intent parameter "$name" was missing or null.');
  }
  return value;
}
