/// A reader for `project.pbxproj` — the OpenStep-style property list Xcode
/// keeps a project in.
///
/// `install` used to find the Runner target and its build phase by the object
/// ids Flutter's template happens to use. Those ids are not guaranteed: a
/// project generated by another Flutter version, or one that has been through
/// Xcode, can carry different ones, and `String.replaceFirst` against a missing
/// anchor does nothing and says nothing — the files end up referenced but in no
/// build phase, which compiles into an app with no intents and no error.
///
/// So the ids are looked up instead. This parses; it never writes. The edits
/// stay textual so the diff a user sees is four inserted lines rather than a
/// whole file Xcode reformatted — but every anchor is an id this found, and the
/// result is parsed again to prove the edit landed.
library;

class PbxprojException implements Exception {
  PbxprojException(this.message);

  final String message;

  @override
  String toString() => message;
}

class Pbxproj {
  Pbxproj._(this.root);

  final Map<String, Object?> root;

  static Pbxproj parse(String text) {
    final value = _Parser(text).parseDocument();
    if (value is! Map<String, Object?>) {
      throw PbxprojException('project.pbxproj does not hold a dictionary.');
    }
    return Pbxproj._(value);
  }

  /// Every object in the file, keyed by its 24-hex-digit id.
  Map<String, Object?> get objects {
    final o = root['objects'];
    if (o is! Map<String, Object?>) {
      throw PbxprojException('project.pbxproj has no objects dictionary.');
    }
    return o;
  }

  /// `objectVersion` — 77 and above is where Xcode 16's synchronized folder
  /// groups appear, and with them a project that may not list files at all.
  int? get objectVersion => int.tryParse('${root['objectVersion']}');

  Map<String, Object?>? object(String? id) {
    final o = id == null ? null : objects[id];
    return o is Map<String, Object?> ? o : null;
  }

  String? isaOf(String id) => object(id)?['isa'] as String?;

  Iterable<String> idsWithIsa(String isa) =>
      objects.keys.where((id) => isaOf(id) == isa);

  /// Ids listed under [key] of [id], skipping anything that is not a list.
  List<String> childIds(String id, String key) {
    final raw = object(id)?[key];
    return raw is List ? raw.whereType<String>().toList() : const [];
  }

  /// A target's display name, which is what the user knows it by.
  String? nameOf(String id) =>
      object(id)?['name'] as String? ?? object(id)?['path'] as String?;

  List<String> get nativeTargetNames => [
    for (final id in idsWithIsa('PBXNativeTarget')) ?nameOf(id),
  ];

  String? nativeTargetNamed(String name) {
    for (final id in idsWithIsa('PBXNativeTarget')) {
      if (nameOf(id) == name) return id;
    }
    return null;
  }

  /// The Sources phase of [targetId].
  ///
  /// Found through the target rather than by isa alone: a Flutter project has
  /// two, and putting the generated Swift in RunnerTests' phase would compile
  /// the intents into the test bundle, where the OS never looks.
  String? sourcesPhaseOf(String targetId) {
    for (final phase in childIds(targetId, 'buildPhases')) {
      if (isaOf(phase) == 'PBXSourcesBuildPhase') return phase;
    }
    return null;
  }

  String? get mainGroupId =>
      object(idsWithIsa('PBXProject').firstOrNull)?['mainGroup'] as String?;

  /// A direct child group of [parentId] whose name or path is [name].
  String? childGroupNamed(String parentId, String name) {
    for (final id in childIds(parentId, 'children')) {
      if (isaOf(id) == 'PBXGroup' && nameOf(id) == name) return id;
    }
    return null;
  }

  /// True when the project uses Xcode 16 synchronized folder groups.
  ///
  /// Those add a directory wholesale, so a project using one for the app's
  /// sources already compiles whatever `sync` writes — and adding explicit file
  /// references on top would build the same file twice.
  bool get usesSynchronizedFolders => objects.keys.any(
    (id) => isaOf(id)?.startsWith('PBXFileSystemSynchronized') ?? false,
  );

  /// The `PBXBuildFile` in [phaseId] that compiles [fileRefId], if any.
  String? buildFileFor(String phaseId, String fileRefId) {
    for (final id in childIds(phaseId, 'files')) {
      if (object(id)?['fileRef'] == fileRefId) return id;
    }
    return null;
  }

  /// The child of [groupId] whose `path` is [path], if any.
  String? fileRefIn(String groupId, String path) {
    for (final id in childIds(groupId, 'children')) {
      if (object(id)?['path'] == path) return id;
    }
    return null;
  }
}

/// Recursive-descent reader for the subset of the format Xcode emits.
///
/// Comments are dropped: they are decoration Xcode regenerates, and the ids
/// they annotate are what everything here works from.
class _Parser {
  _Parser(this.src);

  final String src;
  int i = 0;

  Object? parseDocument() {
    _skip();
    final value = _value();
    _skip();
    return value;
  }

  Object? _value() {
    if (i >= src.length) {
      throw PbxprojException('Unexpected end of project.pbxproj.');
    }
    return switch (src[i]) {
      '{' => _dict(),
      '(' => _array(),
      _ => _string(),
    };
  }

  Map<String, Object?> _dict() {
    _expect('{');
    final out = <String, Object?>{};
    while (true) {
      _skip();
      if (i >= src.length) {
        throw PbxprojException('Unterminated { in project.pbxproj.');
      }
      if (src[i] == '}') {
        i++;
        return out;
      }
      final key = _string();
      _skip();
      _expect('=');
      _skip();
      out[key] = _value();
      _skip();
      if (i < src.length && src[i] == ';') i++;
    }
  }

  List<Object?> _array() {
    _expect('(');
    final out = <Object?>[];
    while (true) {
      _skip();
      if (i >= src.length) {
        throw PbxprojException('Unterminated ( in project.pbxproj.');
      }
      if (src[i] == ')') {
        i++;
        return out;
      }
      out.add(_value());
      _skip();
      if (i < src.length && src[i] == ',') i++;
    }
  }

  String _string() {
    if (i < src.length && src[i] == '"') return _quoted();

    final start = i;
    while (i < src.length && !_isDelimiter(i)) {
      i++;
    }
    if (i == start) {
      throw PbxprojException(
        'Unexpected "${src[i]}" at offset $i in project.pbxproj.',
      );
    }
    return src.substring(start, i);
  }

  String _quoted() {
    i++; // opening quote
    final b = StringBuffer();
    while (i < src.length) {
      final c = src[i];
      if (c == r'\') {
        if (i + 1 >= src.length) break;
        b.write(switch (src[i + 1]) {
          'n' => '\n',
          't' => '\t',
          final other => other,
        });
        i += 2;
        continue;
      }
      if (c == '"') {
        i++;
        return b.toString();
      }
      b.write(c);
      i++;
    }
    throw PbxprojException('Unterminated string in project.pbxproj.');
  }

  /// A bare word ends at structure or whitespace — but not at a `/`, which is
  /// ordinary inside a path like `Runner/Info.plist` unless it opens a comment.
  bool _isDelimiter(int at) {
    final c = src[at];
    if (c.trim().isEmpty) return true;
    if ('{}()=;,"'.contains(c)) return true;
    if (c == '/' &&
        at + 1 < src.length &&
        (src[at + 1] == '*' || src[at + 1] == '/')) {
      return true;
    }
    return false;
  }

  void _expect(String c) {
    if (i >= src.length || src[i] != c) {
      throw PbxprojException(
        'Expected "$c" at offset $i in project.pbxproj, found '
        '"${i < src.length ? src[i] : "end of file"}".',
      );
    }
    i++;
  }

  void _skip() {
    while (i < src.length) {
      final c = src[i];
      if (c.trim().isEmpty) {
        i++;
        continue;
      }
      if (c == '/' && i + 1 < src.length && src[i + 1] == '*') {
        final end = src.indexOf('*/', i + 2);
        if (end < 0) {
          throw PbxprojException('Unterminated comment in project.pbxproj.');
        }
        i = end + 2;
        continue;
      }
      if (c == '/' && i + 1 < src.length && src[i + 1] == '/') {
        final end = src.indexOf('\n', i + 2);
        i = end < 0 ? src.length : end + 1;
        continue;
      }
      return;
    }
  }
}
