// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents sync

package dev.osintents.appfunctions_probe

import androidx.annotation.RequiresApi
import androidx.appfunctions.AppFunction
import androidx.appfunctions.AppFunctionSerializable
import androidx.appfunctions.AppFunctionService
import androidx.appfunctions.AppFunctionServiceEntryPoint
import dev.osintents.os_intents_android.OsIntentsBridge

/** Parameters for "Add task". */
@AppFunctionSerializable(isDescribedByKDoc = true)
data class AddTaskParams(
    /** The title of the task */
    val title: String,
    /** Due date */
    val dueDate: Long?,
)

/** Parameters for "Tasks due today". */
@AppFunctionSerializable(isDescribedByKDoc = true)
data class DueTodayParams(
    /** Unused; this action takes no input. */
    val unused: Boolean = true,
)

/** What an os_intents action answers with. */
@AppFunctionSerializable(isDescribedByKDoc = true)
data class OsIntentsReply(
    /** What the assistant should say. */
    val spoken: String,
)

/**
 * Hosts every action this app exposes to on-device agents.
 *
 * KSP generates the concrete `OsIntentsAppFunctionService` from this class,
 * along with `os_intents_app_functions.xml`.
 */
@RequiresApi(36)
@AppFunctionServiceEntryPoint(
    serviceName = "OsIntentsAppFunctionService",
    appFunctionXmlFileName = "os_intents_app_functions",
)
abstract class BaseOsIntentsAppFunctionService : AppFunctionService() {

    /**
     * Creates a new task in the Inbox
     *
     * @param params the values for this action
     */
    @AppFunction(isDescribedByKDoc = true)
    suspend fun addTask(params: AddTaskParams): OsIntentsReply {
        val outcome = OsIntentsBridge.invoke(
            context = applicationContext,
            id = "addTask",
            args = mapOf(
                "title" to params.title,
                "dueDate" to params.dueDate,
            ),
        )
        return OsIntentsReply(spoken = outcome.spoken ?: "")
    }

    /**
     * Tasks due today
     *
     * @param params the values for this action
     */
    @AppFunction(isDescribedByKDoc = true)
    suspend fun dueToday(params: DueTodayParams): OsIntentsReply {
        val stored = OsIntentsBridge.staticResult(
            applicationContext,
            "dueToday",
        )
        if (stored != null) {
            return OsIntentsReply(spoken = stored["spoken"] as? String ?: "")
        }
        val outcome = OsIntentsBridge.invoke(
            context = applicationContext,
            id = "dueToday",
            args = emptyMap(),
        )
        return OsIntentsReply(spoken = outcome.spoken ?: "")
    }

    override fun onDestroy() {
        OsIntentsBridge.shutdown()
        super.onDestroy()
    }
}
