// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents sync

package dev.osintents.appfunctions_probe

import dev.osintents.os_intents_android.OsIntentsBridge
import io.flutter.plugins.GeneratedPluginRegistrant

/**
 * Call once from `Application.onCreate`.
 *
 * Unlike iOS, where the plugin finds its setup class through the
 * ObjC runtime, an AppFunctionService can start with no Activity and
 * no plugin registration having happened, so there is nothing to hook.
 */
object OsIntentsSetup {
    fun configure() {
        OsIntentsBridge.entrypointLibraryUri = "package:appfunctions_probe/intents.dart"
        OsIntentsBridge.pluginRegistrantCallback = { engine ->
            GeneratedPluginRegistrant.registerWith(engine)
        }
    }
}
