import 'model.dart';

/// Emits the Dart half: a registry mapping intent ids to the user's functions.
///
/// This is what `OsIntents.install()` receives, and what `IntentHarness` walks
/// in tests.
String emitDartRegistry(Manifest manifest) {
  final b = StringBuffer();

  b.writeln('// GENERATED BY os_intents_gen — do not edit.');
  b.writeln('// Source: ${manifest.source}');
  b.writeln();

  if (manifest.intents.isEmpty) {
    b.writeln('// No @AppIntent functions found in this library.');
    b.writeln('final IntentRegistry \$osIntentsRegistry =');
    b.writeln('    const IntentRegistry(<String, IntentBinding>{});');
    return b.toString();
  }

  final queryable = manifest.entities.where((e) => e.hasQuery).toList();

  final entitiesByType = {for (final e in manifest.entities) e.typeName: e};

  b.writeln('/// Every intent declared in this library, keyed by its id.');
  b.writeln('///');
  b.writeln('/// Pass this to `OsIntents.install()` in `main()`, and to');
  b.writeln('/// `IntentHarness` in tests.');
  b.writeln('final IntentRegistry \$osIntentsRegistry = IntentRegistry({');
  for (final intent in manifest.intents) {
    // Entity parameters have to be resolved before the call, so those bindings
    // are async.
    final needsAwait = intent.params.any((p) => p.type == ParamType.entity);
    final arrow = needsAwait ? '(args) async =>' : '(args) =>';

    b.writeln("  '${intent.id}': IntentBinding(");
    b.writeln("    id: '${intent.id}',");
    if (intent.params.isEmpty) {
      b.writeln('    invoke: $arrow ${intent.functionName}(),');
    } else {
      b.writeln('    invoke: $arrow ${intent.functionName}(');
      for (final p in intent.params) {
        b.writeln('      ${p.name}: ${_decode(p, entitiesByType)},');
      }
      b.writeln('    ),');
    }
    b.writeln('  ),');
  }
  b.write('}');

  if (queryable.isEmpty) {
    b.writeln(');');
    return b.toString();
  }

  // Entity queries are answered by the OS *before* a handler runs, so these
  // have to be registered even though nothing in the app calls them.
  b.writeln(', entities: {');
  for (final e in queryable) {
    b.writeln("  '${e.typeName}': EntityBinding(");
    b.writeln("    typeName: '${e.typeName}',");
    b.writeln(
      '    byIds: (ids) async => '
      '(await ${e.queryClassName}().byIds(ids)).map(_encode${e.typeName}).toList(),',
    );
    b.writeln(
      '    matching: (query) async => '
      '(await ${e.queryClassName}().matching(query)).map(_encode${e.typeName}).toList(),',
    );
    b.writeln(
      '    suggested: () async => '
      '(await ${e.queryClassName}().suggested()).map(_encode${e.typeName}).toList(),',
    );
    b.writeln('  ),');
  }
  b.writeln('});');

  return b.toString();
}

/// Reads one argument out of the wire map, converting where the channel cannot
/// carry the Dart type directly.
String _decode(ParamSpec p, Map<String, EntitySpec> entities) {
  final raw = "args['${p.name}']";

  if (p.type == ParamType.entity) {
    // The OS resolved the entity to an identifier; turn it back into the
    // object the handler declared, using the user's own EntityQuery.
    final entity = entities[p.entityTypeName];
    final expr =
        '_resolve${entity?.typeName ?? p.entityTypeName}'
        '($raw as String?)';
    return p.isRequired ? "_require(await $expr, '${p.name}')" : 'await $expr';
  }

  final expr = switch (p.type) {
    // Dates cross the channel as epoch milliseconds: MethodChannel has no
    // DateTime, and sending ISO strings loses the timezone on Android.
    ParamType.dateTime =>
      '$raw == null ? null : '
          'DateTime.fromMillisecondsSinceEpoch($raw! as int, isUtc: true)',
    ParamType.string => '$raw as String?',
    ParamType.int_ => '$raw as int?',
    ParamType.double_ => '($raw as num?)?.toDouble()',
    ParamType.bool_ => '$raw as bool?',
    ParamType.entity => throw StateError('handled above'),
    // An enum crosses as its constant's own name, so the decode is a lookup by
    // name. `byName` throws on an unknown one, which is the right shape: a
    // value the system invented is a bug, not a null.
    ParamType.enum_ =>
      '$raw == null ? null : '
          '${p.enumTypeName}.values.byName($raw! as String)',
  };

  return p.isRequired ? "_require($expr, '${p.name}')" : expr;
}

/// The headless isolate's entry point, emitted only when some intent asks for
/// it.
///
/// `@pragma('vm:entry-point')` is not decoration: nothing in Dart references
/// this function, so tree shaking removes it in release builds and the native
/// side then fails to start the engine with a bare "false" from `run()`.
String emitBackgroundEntrypoint(Manifest manifest) {
  final needed = manifest.intents.any((i) => i.needsHeadlessEngine);
  if (!needed) return '';

  return '''

/// Started by the plugin when an Execution.background intent fires with no UI
/// engine running. Separate isolate: nothing here shares memory with the app.
@pragma('vm:entry-point')
Future<void> osIntentsBackgroundEntrypoint() =>
    OsIntents.installBackground(\$osIntentsRegistry);
''';
}

/// Helpers appended once per generated library, only when something needs them.
String emitDartHelpers(Manifest manifest) {
  final b = StringBuffer();

  final needsRequire = manifest.intents.any(
    (i) => i.params.any((p) => p.isRequired),
  );
  if (needsRequire) {
    b.write('''

/// Throws a message the OS can surface, rather than a bare null check.
T _require<T>(T? value, String name) {
  if (value == null) {
    throw ArgumentError('Intent parameter "\$name" was missing or null.');
  }
  return value;
}
''');
  }

  // One resolver helper per entity actually used as a parameter.
  final used = <String>{
    for (final i in manifest.intents)
      for (final p in i.params)
        if (p.type == ParamType.entity && p.entityTypeName != null)
          p.entityTypeName!,
  };

  // Encoders for every queryable entity. The shape must match what the
  // generated Swift `init(wire:)` reads, so both are emitted from one spec.
  for (final entity in manifest.entities) {
    if (!entity.hasQuery) continue;
    final fields = [
      "        'id': e.${entity.idProperty},",
      for (final p in entity.properties) "        '${p.name}': e.${p.name},",
    ].join('\n');
    b.write('''

/// Flattens a ${entity.dartClassName} for the method channel.
Map<String, Object?> _encode${entity.typeName}(${entity.dartClassName} e) => {
$fields
      };
''');
  }

  for (final entity in manifest.entities) {
    if (!used.contains(entity.typeName)) continue;
    b.write('''

/// Turns the identifier the OS resolved back into a ${entity.dartClassName},
/// using the ${entity.queryClassName} declared with @EntityQuery.
Future<${entity.dartClassName}?> _resolve${entity.typeName}(String? id) async {
  if (id == null) return null;
  final found = await ${entity.queryClassName}().byIds([id]);
  return found.isEmpty ? null : found.first;
}
''');
  }

  return b.toString();
}
