import 'dart:io';

import 'package:os_intents_cli/src/install.dart';
import 'package:os_intents_cli/src/pbxproj.dart';
import 'package:test/test.dart';

final _pristine = File(
  'test/fixtures/pristine_project.pbxproj',
).readAsStringSync();

const _files = [
  'OsIntentsBackground.swift',
  'OsIntentsEntities.swift',
  'OsIntentsGenerated.swift',
  'OsIntentsShortcuts.swift',
];

String installInto(String text, {List<String> files = _files, String target = 'Runner'}) =>
    InstallCommand.install(text, files: files, targetName: target);

/// Everything the generated Swift needs in order to be compiled: a reference in
/// the OsIntents group, and a build file in the target's own Sources phase.
Matcher compiledInto(String targetName) => predicate<String>((text) {
  final project = Pbxproj.parse(text);
  final target = project.nativeTargetNamed(targetName);
  if (target == null) return false;
  final phase = project.sourcesPhaseOf(target)!;
  final appGroup = project.childGroupNamed(project.mainGroupId!, targetName)!;
  final group = project.childGroupNamed(appGroup, 'OsIntents');
  if (group == null) return false;
  return _files.every((f) {
    final ref = project.fileRefIn(group, f);
    return ref != null && project.buildFileFor(phase, ref) != null;
  });
}, 'compiles every generated file into $targetName');

void main() {
  group('a template project', () {
    final installed = installInto(_pristine);

    test('ends up compiling the generated Swift', () {
      expect(installed, compiledInto('Runner'));
    });

    test('is still a project file Xcode can read', () {
      expect(() => Pbxproj.parse(installed), returnsNormally);
    });

    test('gets a group whose path resolves to ios/Runner/OsIntents', () {
      final project = Pbxproj.parse(installed);
      final appGroup = project.childGroupNamed(project.mainGroupId!, 'Runner')!;
      final group = project.childGroupNamed(appGroup, 'OsIntents')!;
      expect(project.object(appGroup)!['path'], 'Runner');
      expect(project.object(group)!['path'], 'OsIntents');
      expect(project.object(group)!['sourceTree'], '<group>');
    });

    test('does not touch the test target', () {
      final project = Pbxproj.parse(installed);
      final testPhase = project.sourcesPhaseOf(
        project.nativeTargetNamed('RunnerTests')!,
      );
      final compiled = [
        for (final id in project.childIds(testPhase!, 'files'))
          project.object(project.object(id)!['fileRef'] as String)?['path'],
      ];
      expect(compiled, isNot(contains('OsIntentsGenerated.swift')));
    });

    test('leaves the existing sources compiled', () {
      final project = Pbxproj.parse(installed);
      final phase = project.sourcesPhaseOf(project.nativeTargetNamed('Runner')!)!;
      final compiled = [
        for (final id in project.childIds(phase, 'files'))
          project.object(project.object(id)!['fileRef'] as String)?['path'],
      ];
      expect(compiled, contains('AppDelegate.swift'));
      expect(compiled, containsAll(_files));
    });

    test('is a small edit, not a rewritten file', () {
      final before = _pristine.split('\n').length;
      final after = installed.split('\n').length;
      // Four references, four build files, four group children, one group.
      expect(after - before, lessThan(25));
    });
  });

  group('running it again', () {
    test('changes nothing at all', () {
      final once = installInto(_pristine);
      expect(installInto(once), same(once));
    });

    test('produces the same ids every time', () {
      expect(installInto(_pristine), installInto(_pristine));
    });
  });

  group('a project whose ids are not the template ones', () {
    // The reason for the rewrite: install used to anchor on the object ids
    // Flutter's template happens to use, and a project generated by another
    // version — or edited in Xcode — silently got no build phase entries.
    final renamed = _pristine
        .replaceAll('97C146EA1CF9000F007C117D', 'AAAA46EA1CF9000F007C117D')
        .replaceAll('97C146F01CF9000F007C117D', 'BBBB46F01CF9000F007C117D');

    test('is installed into all the same', () {
      expect(installInto(renamed), compiledInto('Runner'));
    });
  });

  group('a project half-installed by an earlier run', () {
    test('has the missing build phase entry repaired', () {
      final installed = installInto(_pristine);
      final project = Pbxproj.parse(installed);
      final phase = project.sourcesPhaseOf(project.nativeTargetNamed('Runner')!)!;
      final ref = project.fileRefIn(
        project.childGroupNamed(
          project.childGroupNamed(project.mainGroupId!, 'Runner')!,
          'OsIntents',
        )!,
        'OsIntentsGenerated.swift',
      )!;
      final buildFile = project.buildFileFor(phase, ref)!;

      // Exactly the state the old silent no-op produced: referenced, grouped,
      // and never compiled.
      final broken = installed.replaceFirst(
        RegExp('\\s*$buildFile /\\* OsIntentsGenerated.swift in Sources \\*/,'),
        '',
      );
      expect(broken, isNot(compiledInto('Runner')));
      expect(installInto(broken), compiledInto('Runner'));
    });
  });

  group('what it refuses to do', () {
    test('an unknown target is named, with the ones that exist', () {
      expect(
        () => installInto(_pristine, target: 'MyApp'),
        throwsA(
          isA<PbxprojException>().having(
            (e) => e.message,
            'message',
            allOf(contains('MyApp'), contains('Runner'), contains('RunnerTests')),
          ),
        ),
      );
    });

    test('a file already referenced elsewhere stops the edit', () {
      // A user who added the generated file by hand: installing on top would
      // compile it twice.
      final conflicting = _pristine.replaceFirst(
        RegExp(r'(/\* Begin PBXFileReference section \*/\n)'),
        '/* Begin PBXFileReference section */\n'
            '\t\tFFFFFFFFFFFFFFFFFFFFFFFF /* OsIntentsGenerated.swift */ = '
            '{isa = PBXFileReference; lastKnownFileType = sourcecode.swift; '
            'path = OsIntentsGenerated.swift; sourceTree = "<group>"; };\n',
      );
      expect(
        () => installInto(conflicting),
        throwsA(
          isA<PbxprojException>().having(
            (e) => e.message,
            'message',
            contains('already referenced elsewhere'),
          ),
        ),
      );
    });

    test('a file that is not a project is refused', () {
      expect(() => installInto('nonsense'), throwsA(isA<PbxprojException>()));
    });

    test('a project with no group for the app sources is refused', () {
      final noGroup = _pristine.replaceAll(
        '97C146F01CF9000F007C117D /* Runner */,',
        '',
      );
      expect(
        () => installInto(noGroup),
        throwsA(
          isA<PbxprojException>().having(
            (e) => e.message,
            'message',
            contains('Could not find a "Runner" group'),
          ),
        ),
      );
    });
  });
}
