import 'dart:io';

import 'package:os_intents_cli/src/install.dart';
import 'package:os_intents_cli/src/pbxproj.dart';
import 'package:test/test.dart';

final _pristine = File(
  'test/fixtures/pristine_project.pbxproj',
).readAsStringSync();

const _files = [
  'OsIntentsDonations.swift',
  'OsIntentsBackground.swift',
  'OsIntentsEntities.swift',
  'OsIntentsGenerated.swift',
  'OsIntentsShortcuts.swift',
];

String installInto(
  String text, {
  List<String> files = _files,
  String target = 'Runner',
}) => InstallCommand.install(text, files: files, targetName: target);

/// Everything the generated Swift needs in order to be compiled: a reference in
/// the OsIntents group, and a build file in the target's own Sources phase.
Matcher compiledInto(String targetName) => predicate<String>((text) {
  final project = Pbxproj.parse(text);
  final target = project.nativeTargetNamed(targetName);
  if (target == null) return false;
  final phase = project.sourcesPhaseOf(target)!;
  final appGroup = project.childGroupNamed(project.mainGroupId!, targetName)!;
  final group = project.childGroupNamed(appGroup, 'OsIntents');
  if (group == null) return false;
  return _files.every((f) {
    final ref = project.fileRefIn(group, f);
    return ref != null && project.buildFileFor(phase, ref) != null;
  });
}, 'compiles every generated file into $targetName');

void main() {
  group('a template project', () {
    final installed = installInto(_pristine);

    test('ends up compiling the generated Swift', () {
      expect(installed, compiledInto('Runner'));
    });

    test('is still a project file Xcode can read', () {
      expect(() => Pbxproj.parse(installed), returnsNormally);
    });

    test('gets a group whose path resolves to ios/Runner/OsIntents', () {
      final project = Pbxproj.parse(installed);
      final appGroup = project.childGroupNamed(project.mainGroupId!, 'Runner')!;
      final group = project.childGroupNamed(appGroup, 'OsIntents')!;
      expect(project.object(appGroup)!['path'], 'Runner');
      expect(project.object(group)!['path'], 'OsIntents');
      expect(project.object(group)!['sourceTree'], '<group>');
    });

    test('does not touch the test target', () {
      final project = Pbxproj.parse(installed);
      final testPhase = project.sourcesPhaseOf(
        project.nativeTargetNamed('RunnerTests')!,
      );
      final compiled = [
        for (final id in project.childIds(testPhase!, 'files'))
          project.object(project.object(id)!['fileRef'] as String)?['path'],
      ];
      expect(compiled, isNot(contains('OsIntentsGenerated.swift')));
    });

    test('leaves the existing sources compiled', () {
      final project = Pbxproj.parse(installed);
      final phase = project.sourcesPhaseOf(
        project.nativeTargetNamed('Runner')!,
      )!;
      final compiled = [
        for (final id in project.childIds(phase, 'files'))
          project.object(project.object(id)!['fileRef'] as String)?['path'],
      ];
      expect(compiled, contains('AppDelegate.swift'));
      expect(compiled, containsAll(_files));
    });

    test('is a small edit, not a rewritten file', () {
      final before = _pristine.split('\n').length;
      final after = installed.split('\n').length;
      // A reference, a build file, a group child and a phase entry per file,
      // plus the seven lines of the group itself.
      expect(after - before, lessThan(_files.length * 4 + 10));
    });
  });

  group('running it again', () {
    test('changes nothing at all', () {
      final once = installInto(_pristine);
      expect(installInto(once), same(once));
    });

    test('produces the same ids every time', () {
      expect(installInto(_pristine), installInto(_pristine));
    });
  });

  group('a project whose ids are not the template ones', () {
    // The reason for the rewrite: install used to anchor on the object ids
    // Flutter's template happens to use, and a project generated by another
    // version — or edited in Xcode — silently got no build phase entries.
    final renamed = _pristine
        .replaceAll('97C146EA1CF9000F007C117D', 'AAAA46EA1CF9000F007C117D')
        .replaceAll('97C146F01CF9000F007C117D', 'BBBB46F01CF9000F007C117D');

    test('is installed into all the same', () {
      expect(installInto(renamed), compiledInto('Runner'));
    });
  });

  group('a project half-installed by an earlier run', () {
    test('has the missing build phase entry repaired', () {
      final installed = installInto(_pristine);
      final project = Pbxproj.parse(installed);
      final phase = project.sourcesPhaseOf(
        project.nativeTargetNamed('Runner')!,
      )!;
      final ref = project.fileRefIn(
        project.childGroupNamed(
          project.childGroupNamed(project.mainGroupId!, 'Runner')!,
          'OsIntents',
        )!,
        'OsIntentsGenerated.swift',
      )!;
      final buildFile = project.buildFileFor(phase, ref)!;

      // Exactly the state the old silent no-op produced: referenced, grouped,
      // and never compiled.
      final broken = installed.replaceFirst(
        RegExp('\\s*$buildFile /\\* OsIntentsGenerated.swift in Sources \\*/,'),
        '',
      );
      expect(broken, isNot(compiledInto('Runner')));
      expect(installInto(broken), compiledInto('Runner'));
    });
  });

  group('what it refuses to do', () {
    test('an unknown target is named, with the ones that exist', () {
      expect(
        () => installInto(_pristine, target: 'MyApp'),
        throwsA(
          isA<PbxprojException>().having(
            (e) => e.message,
            'message',
            allOf(
              contains('MyApp'),
              contains('Runner'),
              contains('RunnerTests'),
            ),
          ),
        ),
      );
    });

    test('a file already referenced elsewhere stops the edit', () {
      // A user who added the generated file by hand: installing on top would
      // compile it twice.
      final conflicting = _pristine.replaceFirst(
        RegExp(r'(/\* Begin PBXFileReference section \*/\n)'),
        '/* Begin PBXFileReference section */\n'
        '\t\tFFFFFFFFFFFFFFFFFFFFFFFF /* OsIntentsGenerated.swift */ = '
        '{isa = PBXFileReference; lastKnownFileType = sourcecode.swift; '
        'path = OsIntentsGenerated.swift; sourceTree = "<group>"; };\n',
      );
      expect(
        () => installInto(conflicting),
        throwsA(
          isA<PbxprojException>().having(
            (e) => e.message,
            'message',
            contains('already referenced elsewhere'),
          ),
        ),
      );
    });

    test('a file that is not a project is refused', () {
      expect(() => installInto('nonsense'), throwsA(isA<PbxprojException>()));
    });

    test('a project with no group for the app sources is refused', () {
      final noGroup = _pristine.replaceAll(
        '97C146F01CF9000F007C117D /* Runner */,',
        '',
      );
      expect(
        () => installInto(noGroup),
        throwsA(
          isA<PbxprojException>().having(
            (e) => e.message,
            'message',
            contains('Could not find a "Runner" group'),
          ),
        ),
      );
    });
  });

  // The one thing about this edit that was reasoned about rather than
  // observed: what happens when something else rewrites the project.
  //
  // And it is not hypothetical. CocoaPods rewrites project.pbxproj on every
  // `pod install`, which is every `flutter build ios`, so the real sequence for
  // every consumer is: install, then a full re-serialisation by somebody else.
  // This fixture is the template project with the generated Swift installed,
  // then saved by CocoaPods' own serialiser — captured from a real round trip.
  group('after something else rewrites the project', () {
    final rewritten = File(
      'test/fixtures/cocoapods_rewritten.pbxproj',
    ).readAsStringSync();

    test('it is a genuine reformat, not a copy of what install wrote', () {
      // Otherwise this whole group would be checking nothing. CocoaPods sorts
      // every section by object id, so our four files end up interleaved with
      // the template's rather than at the top where they were inserted.
      expect(rewritten, isNot(installInto(_pristine)));
      expect(
        rewritten.split('\n').length,
        installInto(_pristine).split('\n').length,
      );
    });

    test('every generated file is still compiled', () {
      expect(rewritten, compiledInto('Runner'));
      expect(InstallCommand.notCompiled(rewritten, files: _files), isEmpty);
    });

    test('running install again changes nothing', () {
      // The point of anchoring on ids read from the parsed project rather than
      // on the shape of the surrounding text: a reordered file is the same
      // project, and a second insertion would compile everything twice.
      expect(installInto(rewritten), same(rewritten));
    });

    test('a project rewritten before install is installed into normally', () {
      // A clean round trip through the same serialiser is byte-identical to
      // the template, which is why there is no second fixture for this.
      expect(installInto(_pristine), compiledInto('Runner'));
    });
  });

  group('a project Xcode has modernised', () {
    // Xcode 16 converts projects to objectVersion 77 with synchronized folder
    // groups, which add a directory wholesale. Everything `sync` writes is then
    // already compiled, and adding explicit references on top would build each
    // file twice — so this refuses, and says why.
    //
    // Modelled the way Xcode actually leaves it: the app's PBXGroup is gone,
    // replaced by a synchronized root group in the same place. A project with
    // both would not be a shape Xcode produces, and install would never reach
    // this branch — it would find the ordinary group and edit it.
    final synchronized = _pristine
        .replaceFirst('objectVersion = 54;', 'objectVersion = 77;')
        .replaceAll('97C146F01CF9000F007C117D /* Runner */,', '')
        .replaceFirst(
          '/* Begin PBXGroup section */\n',
          '/* Begin PBXGroup section */\n'
              '\t\tAAAAAAAAAAAAAAAAAAAAAAAA /* Runner */ = '
              '{isa = PBXFileSystemSynchronizedRootGroup; path = Runner; '
              'sourceTree = "<group>"; };\n',
        );

    test('is detected rather than edited', () {
      expect(Pbxproj.parse(synchronized).usesSynchronizedFolders, isTrue);
    });

    test('is refused with the reason and the version', () {
      expect(
        () => installInto(synchronized),
        throwsA(
          isA<PbxprojException>().having(
            (e) => e.message,
            'message',
            allOf(contains('synchronized folder groups'), contains('77')),
          ),
        ),
      );
    });
  });

  // What `install --check` reports on. The case it exists for is real and has
  // happened here: a new emitter output — OsIntentsEnums.swift — was generated
  // for months and never registered, so it compiled into nothing while every
  // other step in the toolchain reported success.
  group('what is not compiled yet', () {
    List<String> notCompiled(String text, {List<String> files = _files}) =>
        InstallCommand.notCompiled(text, files: files);

    test('is everything, in a project nobody has installed into', () {
      expect(notCompiled(_pristine), _files);
    });

    test('is nothing, once install has run', () {
      expect(notCompiled(installInto(_pristine)), isEmpty);
    });

    test('is the one file a later sync added', () {
      // Install what existed at the time, then ask about a file that did not.
      final earlier = installInto(
        _pristine,
        files: _files.where((f) => f != 'OsIntentsEntities.swift').toList(),
      );
      expect(notCompiled(earlier), ['OsIntentsEntities.swift']);
    });

    test('is a file referenced but left out of the Sources phase', () {
      final installed = installInto(_pristine);
      final project = Pbxproj.parse(installed);
      final phase = project.sourcesPhaseOf(
        project.nativeTargetNamed('Runner')!,
      )!;
      final ref = project.fileRefIn(
        project.childGroupNamed(
          project.childGroupNamed(project.mainGroupId!, 'Runner')!,
          'OsIntents',
        )!,
        'OsIntentsGenerated.swift',
      )!;
      final broken = installed.replaceFirst(
        RegExp(
          '\\s*${project.buildFileFor(phase, ref)!} '
          '/\\* OsIntentsGenerated.swift in Sources \\*/,',
        ),
        '',
      );
      expect(notCompiled(broken), ['OsIntentsGenerated.swift']);
    });
  });

  // A String Catalogue is not a source file, and putting it in the Sources
  // phase is not an error Xcode reports — it simply never reaches the bundle,
  // every lookup falls back to its key, and the app shows "addTask.title"
  // where the title should be. The same silent shape as an uncompiled Swift
  // file, one phase over.
  group('a String Catalogue', () {
    const catalogue = 'OsIntents.xcstrings';
    final installed = installInto(_pristine, files: [..._files, catalogue]);
    final project = Pbxproj.parse(installed);
    final group = project.childGroupNamed(
      project.childGroupNamed(project.mainGroupId!, 'Runner')!,
      'OsIntents',
    )!;

    test('goes into Resources, not Sources', () {
      final target = project.nativeTargetNamed('Runner')!;
      final ref = project.fileRefIn(group, catalogue)!;
      expect(
        project.buildFileFor(project.resourcesPhaseOf(target)!, ref),
        isNotNull,
      );
      expect(
        project.buildFileFor(project.sourcesPhaseOf(target)!, ref),
        isNull,
      );
    });

    test('is typed so Xcode compiles it rather than copying it', () {
      expect(
        project.object(
          project.fileRefIn(group, catalogue)!,
        )!['lastKnownFileType'],
        'text.json.xcstrings',
      );
    });

    test('lands beside the Swift, which is still in Sources', () {
      expect(installed, compiledInto('Runner'));
    });

    test('does not go into the test target\'s Resources phase', () {
      final tests = project.nativeTargetNamed('RunnerTests');
      final phase = tests == null ? null : project.resourcesPhaseOf(tests);
      final ref = project.fileRefIn(group, catalogue)!;
      expect(phase == null ? null : project.buildFileFor(phase, ref), isNull);
    });

    test('is reported by --check when it is not registered', () {
      expect(InstallCommand.notCompiled(_pristine, files: [catalogue]), [
        catalogue,
      ]);
      expect(
        InstallCommand.notCompiled(installed, files: [catalogue]),
        isEmpty,
      );
    });

    test('installing again changes nothing', () {
      expect(
        identical(
          installInto(installed, files: [..._files, catalogue]),
          installed,
        ),
        isTrue,
      );
    });
  });
}
