// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents_cli:os_intents sync

import AppIntents
import Foundation

@available(iOS 16.0, *)
enum PriorityEnum: String, AppEnum, CaseIterable {
  case whenever
  case normal
  case veryUrgent

  static var typeDisplayRepresentation: TypeDisplayRepresentation {
    "Priority"
  }

  static var caseDisplayRepresentations: [PriorityEnum: DisplayRepresentation] {
    [
      .whenever: "Whenever",
      .normal: "Normal",
      .veryUrgent: "Very urgent",
    ]
  }
}

