// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents_cli:os_intents sync

import AppIntents
import Foundation
import UniformTypeIdentifiers

@available(iOS 16.0, *)
enum OsIntentsFiles {
  /// Spills a file the system supplied to disk, so Dart can read it by path.
  static func wire(_ file: IntentFile?) -> [String: Any]? {
    guard let file else { return nil }
    let directory = FileManager.default.temporaryDirectory
      .appendingPathComponent("os_intents", isDirectory: true)
    let target = directory.appendingPathComponent(
      UUID().uuidString + "-" + file.filename
    )
    do {
      try FileManager.default.createDirectory(
        at: directory, withIntermediateDirectories: true
      )
      try file.data.write(to: target)
    } catch {
      // The action itself may still be able to answer, so this reports the
      // parameter as absent rather than failing the whole invocation.
      NSLog("OSINTENTS file %@ could not be staged: %@",
            file.filename, String(describing: error))
      return nil
    }
    var wire: [String: Any] = [
      "path": target.path,
      "filename": file.filename,
    ]
    if let mime = file.type?.preferredMIMEType {
      wire["mimeType"] = mime
    }
    return wire
  }

  /// Rebuilds a file a handler answered with, or one a snippet button carries.
  static func file(fromWire wire: Any?) -> IntentFile? {
    // Nested method-channel maps decode as [AnyHashable: Any], not
    // [String: Any] — the same trap the snippet decoder hit.
    guard let map = wire as? [AnyHashable: Any],
          let path = map["path"] as? String
    else { return nil }
    let url = URL(fileURLWithPath: path)
    let name = map["filename"] as? String ?? url.lastPathComponent
    let type = (map["mimeType"] as? String).flatMap({ UTType(mimeType: $0) })
    return IntentFile(fileURL: url, filename: name, type: type)
  }
}
