// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents_cli:os_intents sync

import AppIntents
import Foundation
import os_intents_ios

@available(iOS 16.0, *)
struct AddTaskOsIntent: AppIntent {
  static let title: LocalizedStringResource = "Add task"
  static let description = IntentDescription("Creates a new task in the Inbox")
  static let openAppWhenRun = false

  @Parameter(title: "Title", requestValueDialog: "What should the task be called?")
  var title: String
  @Parameter(title: "Due date")
  var dueDate: Date?
  @Parameter(title: "Project")
  var project: ProjectEntity?
  @Parameter(title: "Priority")
  var priority: PriorityEnum?

  static var parameterSummary: some ParameterSummary {
    Summary("Add task \(\.$title)") {
      \.$dueDate
      \.$project
      \.$priority
    }
  }

  func perform() async throws -> some IntentResult & ProvidesDialog {
    let outcome = try await OsIntentsBridge.shared.invokeBackground(
      id: "addTask",
      args: [
        "title": title,
        "dueDate": dueDate.map { Int($0.timeIntervalSince1970 * 1000) },
        "project": project?.id,
        "priority": priority?.rawValue,
      ]
    )
    return .result(dialog: IntentDialog(stringLiteral: outcome.spoken ?? ""))
  }
}


@available(iOS 16.0, *)
struct DueTodayOsIntent: AppIntent {
  static let title: LocalizedStringResource = "Tasks due today"
  static let openAppWhenRun = false

  func perform() async throws -> some IntentResult & ProvidesDialog & ShowsSnippetView {
    // Execution.static_: answered from stored state, with no
    // Dart engine started.
    if let stored = OsIntentsBridge.shared.staticResult(for: "dueToday") {
      let outcome = IntentOutcome(wire: stored)
      return .result(dialog: IntentDialog(stringLiteral: outcome.spoken ?? ""), view: OsIntentsSnippetView(
        wire: outcome.snippet,
        button: OsIntentsSnippetActions.builder
      ))
    }
    // Nothing published yet — usually a first run, before the
    // app has had a chance to call publishStatic. Fall back to
    // running the handler rather than answering with silence.
    let outcome = try await OsIntentsBridge.shared.invokeBackground(
      id: "dueToday",
      args: [:]
    )
    return .result(dialog: IntentDialog(stringLiteral: outcome.spoken ?? ""), view: OsIntentsSnippetView(
        wire: outcome.snippet,
        button: OsIntentsSnippetActions.builder
      ))
  }
}


@available(iOS 16.0, *)
struct LogRunOsIntent: AppIntent {
  static let title: LocalizedStringResource = "Log a run"
  static let description = IntentDescription("Records a run against a route")
  static let openAppWhenRun = false

  @Parameter(title: "Route")
  var route: URL
  @Parameter(title: "Elapsed", defaultUnit: .seconds)
  var elapsed: Measurement<UnitDuration>
  @Parameter(title: "Distance", defaultUnit: .meters)
  var distance: Measurement<UnitLength>
  @Parameter(title: "Photo")
  var photo: IntentFile?

  static var parameterSummary: some ParameterSummary {
    Summary("Log a run \(\.$route)") {
      \.$photo
    }
  }

  func perform() async throws -> some IntentResult & ProvidesDialog {
    let outcome = try await OsIntentsBridge.shared.invokeBackground(
      id: "logRun",
      args: [
        "route": route.absoluteString,
        "elapsed": Int(elapsed.converted(to: .seconds).value * 1_000_000),
        "distance": distance.converted(to: .meters).value,
        "photo": OsIntentsFiles.wire(photo),
      ]
    )
    return .result(dialog: IntentDialog(stringLiteral: outcome.spoken ?? ""))
  }
}


@available(iOS 16.0, *)
struct CountOpenTasksOsIntent: AppIntent {
  static let title: LocalizedStringResource = "Count tasks"
  static let description = IntentDescription("How many tasks are open")
  static let openAppWhenRun = false

  func perform() async throws -> some IntentResult & ReturnsValue<Int> & ProvidesDialog {
    let outcome = try await OsIntentsBridge.shared.invokeBackground(
      id: "countOpenTasks",
      args: [:]
    )
    return .result(value: outcome.intValue ?? 0, dialog: IntentDialog(stringLiteral: outcome.spoken ?? ""))
  }
}


@available(iOS 16.0, *)
struct CompleteTaskOsIntent: AppIntent {
  static let title: LocalizedStringResource = "Complete task"
  static let description = IntentDescription("Marks a task as done")
  static let openAppWhenRun = false

  @Parameter(title: "Task")
  var taskId: String

  static var parameterSummary: some ParameterSummary {
    Summary("Complete task \(\.$taskId)")
  }

  func perform() async throws -> some IntentResult & ProvidesDialog {
    if #available(iOS 18.0, *) {
      try await requestConfirmation(
        dialog: IntentDialog("Mark this task as done?")
      )
    } else {
      try await requestConfirmation()
    }
    let outcome = try await OsIntentsBridge.shared.invokeBackground(
      id: "completeTask",
      args: [
        "taskId": taskId,
      ]
    )
    return .result(dialog: IntentDialog(stringLiteral: outcome.spoken ?? ""))
  }
}


