// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents_cli:os_intents sync

import AppIntents
import Foundation
import os_intents_ios

@objc(OsIntentsDonor)
final class OsIntentsDonor: NSObject, OsIntentsDonating {
  func donate(
    id: String,
    wire: [String: Any],
    completion: @escaping (Bool) -> Void
  ) {
    guard #available(iOS 16.0, *) else {
      completion(false)
      return
    }
    Task {
      switch id {
      case "addTask":
        let intent = AddTaskOsIntent()
        if let value = wire["title"] as? String { intent.title = value }
        if let value = (wire["dueDate"] as? NSNumber).map({ Date(timeIntervalSince1970: $0.doubleValue / 1000) }) { intent.dueDate = value }
        if let value = (wire["project"] as? String).map({ ProjectEntity(wire: ["id": $0]) }) { intent.project = value }
        if let value = (wire["priority"] as? String).flatMap({ PriorityEnum(rawValue: $0) }) { intent.priority = value }
        do {
          _ = try await IntentDonationManager.shared.donate(
            intent: intent
          )
          completion(true)
        } catch {
          completion(false)
        }
      case "dueToday":
        let intent = DueTodayOsIntent()
        do {
          _ = try await IntentDonationManager.shared.donate(
            intent: intent
          )
          completion(true)
        } catch {
          completion(false)
        }
      case "logRun":
        let intent = LogRunOsIntent()
        if let value = (wire["route"] as? String).flatMap({ URL(string: $0) }) { intent.route = value }
        if let value = (wire["elapsed"] as? NSNumber).map({ Measurement(value: $0.doubleValue / 1_000_000, unit: UnitDuration.seconds) }) { intent.elapsed = value }
        if let value = (wire["distance"] as? NSNumber).map({ Measurement(value: $0.doubleValue, unit: UnitLength.meters) }) { intent.distance = value }
        if let value = OsIntentsFiles.file(fromWire: wire["photo"]) { intent.photo = value }
        do {
          _ = try await IntentDonationManager.shared.donate(
            intent: intent
          )
          completion(true)
        } catch {
          completion(false)
        }
      case "countOpenTasks":
        let intent = CountOpenTasksOsIntent()
        do {
          _ = try await IntentDonationManager.shared.donate(
            intent: intent
          )
          completion(true)
        } catch {
          completion(false)
        }
      case "completeTask":
        let intent = CompleteTaskOsIntent()
        if let value = wire["taskId"] as? String { intent.taskId = value }
        do {
          _ = try await IntentDonationManager.shared.donate(
            intent: intent
          )
          completion(true)
        } catch {
          completion(false)
        }
      default:
        completion(false)
      }
    }
  }
}
