// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents_cli:os_intents sync

import AppIntents

@available(iOS 16.0, *)
struct OsIntentsShortcuts: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
    AppShortcut(
      intent: AddTaskOsIntent(),
      phrases: [
        "Add a task to \(.applicationName)",
        "New \(.applicationName) task",
      ],
      shortTitle: "Add task",
      systemImageName: "plus.circle"
    )
    AppShortcut(
      intent: DueTodayOsIntent(),
      phrases: [
        "What's due today in \(.applicationName)",
      ],
      shortTitle: "Tasks due today",
      systemImageName: "calendar"
    )
  }
}
