// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents_cli:os_intents sync

import AppIntents
import Foundation
import os_intents_ios

@available(iOS 16.0, macOS 13.0, *)
struct ProjectEntity: AppEntity, Identifiable {
  var id: String
  var name: String?
  var teamName: String?

  static let typeDisplayRepresentation: TypeDisplayRepresentation = "Project"

  var displayRepresentation: DisplayRepresentation {
    DisplayRepresentation(
      title: LocalizedStringResource(stringLiteral: name ?? id),
      subtitle: teamName.map { LocalizedStringResource(stringLiteral: $0) }
    )
  }

  static var defaultQuery = ProjectQuery()
}


@available(iOS 16.0, macOS 13.0, *)
struct ProjectQuery: EntityStringQuery {
  func entities(for identifiers: [String]) async throws -> [ProjectEntity] {
    try await OsIntentsBridge.shared.resolveEntities(
      type: "Project", ids: identifiers
    ).map(ProjectEntity.init(wire:))
  }

  func entities(matching string: String) async throws -> [ProjectEntity] {
    try await OsIntentsBridge.shared.searchEntities(
      type: "Project", query: string
    ).map(ProjectEntity.init(wire:))
  }

  func suggestedEntities() async throws -> [ProjectEntity] {
    try await OsIntentsBridge.shared.suggestedEntities(
      type: "Project"
    ).map(ProjectEntity.init(wire:))
  }
}

@available(iOS 16.0, macOS 13.0, *)
extension ProjectEntity {
  init(wire: [String: Any]) {
    self.id = wire["id"] as? String ?? ""
    self.name = wire["name"] as? String
    self.teamName = wire["teamName"] as? String
  }
}


