// GENERATED BY os_intents — do not edit.
//
// Regenerate with:
//   dart run build_runner build && dart run os_intents_cli:os_intents sync

import AppIntents
import Foundation
import SwiftUI
import os_intents_ios

enum OsIntentsSnippetActions {
  /// nil below iOS 17, where Button(intent:) does not exist.
  @available(iOS 16.0, macOS 13.0, *)
  static var builder: OsIntentsSnippetView.ButtonBuilder? {
    if #available(iOS 17.0, macOS 14.0, *) {
      return button(id:args:label:systemImageName:)
    }
    return nil
  }

  @available(iOS 17.0, macOS 14.0, *)
  static func button(
    id: String,
    args: [String: Any],
    label: String,
    systemImageName: String?
  ) -> AnyView? {
    switch id {
    case "addTask":
      let intent = AddTaskOsIntent()
      if let value = args["title"] as? String { intent.title = value }
      if let value = (args["dueDate"] as? NSNumber).map({ Date(timeIntervalSince1970: $0.doubleValue / 1000) }) { intent.dueDate = value }
      if let value = (args["project"] as? String).map({ ProjectEntity(wire: ["id": $0]) }) { intent.project = value }
      if let value = (args["priority"] as? String).flatMap({ PriorityEnum(rawValue: $0) }) { intent.priority = value }
      return AnyView(
        Button(intent: intent) {
          if let systemImageName {
            Label(label, systemImage: systemImageName)
          } else {
            Text(label)
          }
        }
      )
    case "dueToday":
      let intent = DueTodayOsIntent()
      return AnyView(
        Button(intent: intent) {
          if let systemImageName {
            Label(label, systemImage: systemImageName)
          } else {
            Text(label)
          }
        }
      )
    case "logRun":
      let intent = LogRunOsIntent()
      if let value = (args["route"] as? String).flatMap({ URL(string: $0) }) { intent.route = value }
      if let value = (args["elapsed"] as? NSNumber).map({ Measurement(value: $0.doubleValue / 1_000_000, unit: UnitDuration.seconds) }) { intent.elapsed = value }
      if let value = (args["distance"] as? NSNumber).map({ Measurement(value: $0.doubleValue, unit: UnitLength.meters) }) { intent.distance = value }
      if let value = OsIntentsFiles.file(fromWire: args["photo"]) { intent.photo = value }
      return AnyView(
        Button(intent: intent) {
          if let systemImageName {
            Label(label, systemImage: systemImageName)
          } else {
            Text(label)
          }
        }
      )
    case "countOpenTasks":
      let intent = CountOpenTasksOsIntent()
      return AnyView(
        Button(intent: intent) {
          if let systemImageName {
            Label(label, systemImage: systemImageName)
          } else {
            Text(label)
          }
        }
      )
    case "completeTask":
      let intent = CompleteTaskOsIntent()
      if let value = args["taskId"] as? String { intent.taskId = value }
      return AnyView(
        Button(intent: intent) {
          if let systemImageName {
            Label(label, systemImage: systemImageName)
          } else {
            Text(label)
          }
        }
      )
    default:
      return nil
    }
  }
}
